spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

springdoc:
  swagger-ui:
    oauth:
      client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
      client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
      scopes: openid, profile, email
      use-id-token-with-authorization-code-grant: true
  openapi:
    security:
      - google_oidc: []
      - manual_jwt: []
